#! /usr/bin/env python


import argparse
import os

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

def register():
    parser = argparse.ArgumentParser("advanced cd manipulator")
    parser.add_argument("path", nargs='?', default=os.getcwd(), type=str)
    parser.add_argument('-l', '--list', help='list all saved paths', action='store_true')
    parser.add_argument('-j', '--jump', help='jump to a specified path', nargs=1, action='store', metavar=('num'))
    parser.add_argument('-s', '--save', help='save a current path', action='store_true')
    parser.add_argument('-d', '--delete', help='delete a specified path', nargs=1, action='store', metavar=('num'))
    args = parser.parse_args()

    return args


def load_file():
    file_path = PROJECT_DIR + '/paths.txt'

    with open(file_path, 'r+') as f:
        dir_paths_set = set([(num, line.rstrip()) for num, line in enumerate(f.readlines())])
        dir_paths_list = sorted(dir_paths_set, key=lambda x:x[0])

    return dir_paths_list


def write_file():
    file_path = PROJECT_DIR + '/paths.txt'

    with open(file_path, 'a+') as f:
        f.write(os.getcwd() + '\n')

    make_unique()


def make_unique():
    file_path = PROJECT_DIR + '/paths.txt'

    with open(file_path, 'r+') as f:
        dir_paths_set = set([(num, line) for num, line in enumerate(f.readlines())]) 
        dir_paths_list = sorted(dir_paths_set, key=lambda x:x[0])

    with open(file_path, 'w') as f:
        wrote_list = []
        for path in dir_paths_list:
            if path[1] not in wrote_list:
                f.write(path[1])
                wrote_list.append(path[1])


def manipulation(args):
    if args.list:
        dir_paths_list = load_file()
        for path in dir_paths_list:
            print(path[0], path[1])

    if args.save:
        write_file()


if __name__ == '__main__':
    args = register()
    manipulation(args)

